billing/forms/braintree_payments_forms.py
from django import forms
from django.conf import settings


class BraintreePaymentsForm(forms.Form):
    transaction__customer__first_name = forms.CharField(max_length=50, required=False)
    transaction__customer__last_name = forms.CharField(max_length=50, required=False)
    transaction__customer__company = forms.CharField(max_length=100, required=False)
    transaction__customer__email = forms.EmailField(required=False)
    transaction__customer__phone = forms.CharField(max_length=15, required=False)
    transaction__customer__fax = forms.CharField(max_length=15, required=False)
    transaction__customer__website = forms.URLField(required=False)
    transaction__credit_card__cardholder_name = forms.CharField(max_length=100)
    transaction__credit_card__number = forms.CharField()
    transaction__credit_card__cvv = forms.CharField(max_length=4)
    transaction__credit_card__expiration_date = forms.CharField(max_length=7)

    transaction__billing__first_name = forms.CharField(max_length=50, required=False)
    transaction__billing__last_name = forms.CharField(max_length=50, required=False)
    transaction__billing__company = forms.CharField(max_length=100, required=False)
    transaction__billing__street_address = forms.CharField(widget=forms.Textarea(), required=False)
    transaction__billing__extended_address = forms.CharField(widget=forms.Textarea(), required=False)
    transaction__billing__locality = forms.CharField(max_length=50, required=False)
    transaction__billing__region = forms.CharField(max_length=50, required=False)
    transaction__billing__postal_code = forms.CharField(max_length=10, required=False)
    transaction__billing__country_code_alpha2 = forms.CharField(max_length=2, required=False)
    transaction__billing__country_code_alpha3 = forms.CharField(max_length=3, required=False)
    transaction__billing__country_code_numeric = forms.IntegerField(required=False, min_value=0)
    transaction__billing__country_name = forms.CharField(max_length=50, required=False)

    transaction__shipping__first_name = forms.CharField(max_length=50, required=False)
    transaction__shipping__last_name = forms.CharField(max_length=50, required=False)
    transaction__shipping__company = forms.CharField(max_length=100, required=False)
    transaction__shipping__street_address = forms.CharField(widget=forms.Textarea(), required=False)
    transaction__shipping__extended_address = forms.CharField(widget=forms.Textarea(), required=False)
    transaction__shipping__locality = forms.CharField(max_length=50, required=False)
    transaction__shipping__region = forms.CharField(max_length=50, required=False)
    transaction__shipping__postal_code = forms.CharField(max_length=10, required=False)
    transaction__shipping__country_code_alpha2 = forms.CharField(max_length=2, required=False)
    transaction__shipping__country_code_alpha3 = forms.CharField(max_length=3, required=False)
    transaction__shipping__country_code_numeric = forms.IntegerField(required=False, min_value=0)
    transaction__shipping__country_name = forms.CharField(max_length=50, required=False)

    transaction__options__add_billing_address_to_payment_method = forms.BooleanField(required=False)
    transaction__options__store_shipping_address_in_vault = forms.BooleanField(required=False)
    transaction__options__store_in_vault_on_success = forms.BooleanField(required=False)
    transaction__options__submit_for_settlement = forms.BooleanField(required=False)

    transaction__type = forms.CharField(max_length=10)
    transaction__amount = forms.DecimalField(required=False)
    transaction__order_id = forms.CharField(max_length=50)
    transaction__customer__id = forms.CharField(max_length=50, required=False)
    transaction__credit_card__token = forms.CharField(max_length=50, required=False)
    transaction__payment_method_token = forms.CharField(max_length=50, required=False)

    tr_data = forms.CharField(widget=forms.HiddenInput())

billing/forms/paypal_forms.py
from django import forms


from paypal.standard.forms import (PayPalPaymentsForm,
                                   PayPalEncryptedPaymentsForm)


class MultipleItemsMixin(object):
    """
    Use the initial data as a heuristic to create a form
    that accepts multiple items
    """

    def __init__(self, **kwargs):
        super(MultipleItemsMixin, self).__init__(**kwargs)
        has_multiple_items = False
        if 'initial' in kwargs:
            for k, v in kwargs['initial'].items():
                if k.startswith('amount_'):
                    self.fields[k] = forms.IntegerField(
                        widget=forms.widgets.HiddenInput())
                    has_multiple_items = True
                elif  k.startswith('item_name_'):
                    has_multiple_items = True
                    self.fields[k] = forms.CharField(
                        widget=forms.widgets.HiddenInput())
        if has_multiple_items:
            self.fields['upload'] = forms.IntegerField(
                initial=1,
                widget=forms.widgets.HiddenInput())
            del self.fields['amount']
            del self.fields['item_name']
            self.initial['cmd'] = '_cart'


class MerchantPayPalPaymentsForm(MultipleItemsMixin, PayPalPaymentsForm):
    pass


class MerchantPayPalEncryptedPaymentsForm(MultipleItemsMixin, PayPalEncryptedPaymentsForm):
    pass

billing/forms/stripe_forms.py
from django import forms
import decimal
import datetime

curr_year = datetime.datetime.now().year
month_choices = ((ii, ii) for ii in range(1, 13))
year_choices = ((ii, ii) for ii in range(curr_year, curr_year + 7))


class StripeForm(forms.Form):
    # Small value to prevent non-zero values. Might need a relook
    amount = forms.DecimalField(min_value=decimal.Decimal('0.001'))
    credit_card_number = forms.CharField(max_length=16)
    credit_card_cvc = forms.CharField(max_length=4)
    credit_card_expiration_month = forms.CharField(max_length=2, widget=forms.Select(choices=month_choices))
    credit_card_expiration_year = forms.CharField(max_length=4, widget=forms.Select(choices=year_choices))

billing/forms/world_pay_forms.py
from django import forms
from hashlib import md5
from django.conf import settings


class WPHostedPaymentForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(WPHostedPaymentForm, self).__init__(*args, **kwargs)
        if self.initial:
            self.initial["signatureFields"] = self.initial.get("signatureFields") or "instId:amount:cartId"
            signature_fields = self.initial["signatureFields"].split(":")
            hash_str = ""
            for field in signature_fields:
                hash_str += "%s" % self.initial[field]
                if not signature_fields.index(field) == len(signature_fields) - 1:
                    hash_str += ":"
            md5_hash = md5("%s:%s" % (settings.MERCHANT_SETTINGS["world_pay"]["MD5_SECRET_KEY"],
                                     hash_str)).hexdigest()
            self.initial["signature"] = self.initial.get("signature") or md5_hash

    # recurring(future pay) parameters
    futurePayType = forms.CharField(widget=forms.HiddenInput(), required=False)
    intervalUnit = forms.CharField(widget=forms.HiddenInput(), required=False)
    intervalMult = forms.CharField(widget=forms.HiddenInput(), required=False)
    option = forms.CharField(widget=forms.HiddenInput(), required=False)
    noOfPayments = forms.CharField(widget=forms.HiddenInput(), required=False)
    normalAmount = forms.CharField(widget=forms.HiddenInput(), required=False)
    startDelayUnit = forms.CharField(widget=forms.HiddenInput(), required=False)
    startDelayMult = forms.CharField(widget=forms.HiddenInput(), required=False)

    instId = forms.CharField(widget=forms.HiddenInput)
    cartId = forms.CharField(widget=forms.HiddenInput)
    amount = forms.DecimalField(widget=forms.HiddenInput)
    currency = forms.CharField(widget=forms.HiddenInput, initial="USD")
    desc = forms.CharField(widget=forms.HiddenInput)
    testMode = forms.CharField(widget=forms.HiddenInput)
    signatureFields = forms.CharField(widget=forms.HiddenInput)
    signature = forms.CharField(widget=forms.HiddenInput)

    #override Country field
    # country = CountryField(initial="AU")

billing/templates/billing/amazon_fps.html
<a href="{{ integration.link_url }}"><img src="http://g-ecx.images-amazon.com/images/G/01/cba/b/p3.gif" alt="Amazon Payments" /></a>

billing/templates/billing/authorize_net_dpm.html
<form method="post" action="{{ integration.service_url }}">
  {{ integration.generate_form.as_p }}
  <p><input type="submit" value="Pay" /></p>
</form>

billing/templates/billing/authorize_net_relay_snippet.html
<html>
  <head>
    <script language="javascript">
      <!--
          window.location="{{ redirect_url }}";
      //-->
    </script>
  </head>
  <body>
    <noscript>
      <meta http-equiv="refresh" content="1;url={{ redirect_url }}">
    </noscript>
  </body>
</html>

billing/templates/billing/braintree_payments.html
<form method="post" action="{{ integration.service_url }}">
  {{ integration.generate_form.as_p }}
</form>

billing/templates/billing/eway.html
<form method="post" action="{{ integration.service_url }}">
    {{ integration.generate_form.as_p }}
    <input type="submit"/>
</form>

billing/templates/billing/google_checkout.html
<form action="{{ integration.service_url }}" method="post">
  <input type="hidden" name="cart" value="{{ integration.generate_cart_xml }}" />
  <input type="hidden" name="signature" value="{{ integration.signature }}" />
  <input type="image" name="Google Checkout" alt="Fast checkout through Google" src="{{ integration.button_image_url }}" height="{{ integration.button_height }}" width="{{ integration.button_width }}" />
</form>

billing/templates/billing/ogone_payments.html
<form method="post" action="{{ integration.service_url }}">
  {{ integration.generate_form.as_p }}
  <button type="submit" class="btn btn-primary">Checkout!</button>
</form>

billing/templates/billing/paypal.html
{% if integration.test_mode %}
    {{ integration.generate_form.sandbox }}
{% else %}
    {{ integration.generate_form.render }}
{% endif %}

billing/templates/billing/stripe.html
{% load crispy_forms_tags %}

<div class="payment-errors"></div>{% load future %}
<script type="text/javascript" src="//code.jquery.com/jquery.min.js"></script>
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<script type="text/javascript">
$(document).ready(function() {
  Stripe.setPublishableKey('{{ integration.publishable_key }}');

  function stripeResponseHandler(status, response) {
    if (response.error) {
      $(".payment-errors").html(response.error.message);
    } else {
      console.log(response);
      var token = response['id'];
      $("#payment-form input[name=stripeToken]").val(token);
      var redactedCCNum = "";
      for (var ii=0; ii < 12; ii++) {
          redactedCCNum += "x";
      }
      var originalCCNum = $("#stripe-form input[name=credit_card_number]").val();
      redactedCCNum += originalCCNum.substring(originalCCNum.length-4, originalCCNum.length);
      $("#payment-form input[name=redactedCCNum]").val(redactedCCNum);
      var expMonth = $("#stripe-form input[name=credit_card_expiration_month]").val();
      var expYear = $("#stripe-form input[name=credit_card_expiration_year]").val();
      $("#payment-form input[name=credit_card_expiration_month]").val(expMonth);
      $("#payment-form input[name=credit_card_expiration_year]").val(expYear);
      $("#payment-form").get(0).submit();
    }
  }

  $("#stripe-form").submit(function(event) {
    $('.submit-button').attr("disabled", "disabled");
    var amount = $('#id_amount').val(); //amount you want to charge in cents
    Stripe.createToken({
       number: $('#id_credit_card_number').val(),
       cvc: $('#id_credit_card_cvc').val(),
       exp_month: $('#id_credit_card_expiration_month').val(),
       exp_year: $('#id_credit_card_expiration_year').val()
    }, amount, stripeResponseHandler);
    return false;
  });
});
</script>
<form class="form-horizontal well" method="post" id="stripe-form">
    <fieldset>
        <legend>Using Payment Backend: {{ title }}</legend>
        {{ integration.generate_form|crispy }}
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn">Cancel</button>
        </div>
    </fieldset>
</form>

<form method="post" style="display:none;" action="{% url 'stripe_transaction' %}" id="payment-form">{% csrf_token %}
  <input type="hidden" name="credit_card_expiration_month" value="" />
  <input type="hidden" name="credit_card_expiration_year" value="" />
  <input type="hidden" name="redactedCCNumber" value="" />
  <input type="hidden" name="stripeToken" value="" />
</form>

billing/templates/billing/world_pay.html
<form method='post' action='{{ integration.service_url }}'>
    {{ form }}
    <input type='submit' value='Pay through WorldPay'/>
</form>